name: Requirements tests
run-name: Rests with ${{ inputs.tested-branch }} (default master) branch and tests from ${{ github.ref_name }} branch.

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:
    inputs:
      tested-branch:
        description: "Specify the branch."
        required: false
        type: string
        default: master
      include-expression:
        description: "Specify keyword expression for run selected tests, e.g. 'req and (dump_dataset_dictionary or sql)'. Leave empty to run all."
        required: false
        type: string
  schedule:
    - cron: '0 9 * * WED'
    - cron: '0 9 * * SUN'
    
jobs:
  run-reqs-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout the current repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run Tests On Manual Trigger
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "Running manual tests"
        
      - name: Run Tests On Other Triggers
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          echo "Running scheduled tests"

      - name: Build some artifact
        if: always()
        run: |
          echo "Unbelievable" > unbelievable.jar

      - name: Archive
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Important artifact
          path: unbelievable.jar
          retention-days: 2

