name: Using Secrets and Variables
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - ready_for_review
      - labeled
  workflow_dispatch:

jobs:
  test:
    name: Integration Tests (Staging)
    runs-on: ubuntu-20.04
    env:
      PROJECT: test_project_01
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      # performance optimizations https://abbbi.github.io/actions/
      - uses: abbbi/github-actions-tune@v1
      - name: Install java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run integration tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ROBOT_TOKEN: ${{ secrets.STAGING_ROBOT_TOKEN }}
        run: |
          echo "We will be using secret: $ROBOT_TOKEN to log into the project: $PROJECT"

